apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elastic.app.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.elastic.app.name }}
spec:
  selector:
    name: {{ .Values.elastic.app.name }}
  ports:
    - protocol: TCP
      name: client
      port: 9200
      targetPort: 9200
  type: {{ .Values.elastic.service.type }}