apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kibana.app.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.kibana.app.name }}
spec:
  selector:
    name: {{ .Values.kibana.app.name }}
  ports:
    - protocol: TCP
      name: client
      port: 5601
      targetPort: 5601
  type: {{ .Values.kibana.service.type }}