# Default values for burak-es.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: default
elastic:
  replicaCount: 3
  app:
    name: elasticsearch
  image:
    repository: elasticsearch
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "6.8.20"
  service:
    type: LoadBalancer

kibana:
  replicaCount: 1
  app:
    name: kibana
  image:
    repository: kibana
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "6.8.20"
  service:
    type: LoadBalancer



imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   limits:
     cpu: 250m
     memory: 1500Mi
   requests:
     cpu: 250m
     memory: 1500Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

